### ISSUE TITLE
cannot download pretrained model resnet-50 from China!

### ISSUE THREAD

**Issue by zerouuuu** [CVxTz/kinship_prediction#1]
cannot download the model from this website.Because s3.amazon.com is blocked by the "Great Wall" :-(
Can anyone put it on gitgub?

https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5

**Comment by CVxTz** [comment]
Vpn ?

**Comment by CVxTz** [comment]
Or kaggle maybe ?
https://www.kaggle.com/keras/resnet50

**Comment by zerouuuu** [comment]
> Or kaggle maybe ?
> https://www.kaggle.com/keras/resnet50
Thanks a lot, It works.
